### ISSUE TITLE
Cannot run on GitHub Codespace

### ISSUE THREAD

**Issue by Heinrich-XIAO** [Infinite-Chess/infinitechess.org#72]
Running the server with `npm run start` and `npm run watch` (because it still references the start script) and forwarding the ports. The forwarded address gives a [502](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502) error.

**Comment by Naviary2** [comment]
Is this still occurring? Anyone know of a fix for this?

**Comment by Naviary2** [comment]
Closed because as far as I know, this is already resolved.

**Comment by Heinrich-XIAO** [comment]
This still is happening, but now it sometimes gives 403 instead of 502.

**Comment by pihedron** [comment]
Maybe try using Project IDX instead of GitHub Codespaces. It's a much better experience.

**Comment by vladanghene** [comment]
still happening. node runs, port forwarded, browser hits 502.
